<!DOCTYPE html>
<html>
<head>
<title>Insert Inventory</title>
</head>
<body style="background-color: rgb(229,243,247);">
<?php
// Set the variables for the database access:
require_once('includes/initialize.php');

/* This page receives and handles the data generated by "insertInventoryForm.html". */
// Trim the incoming data.

$title = trim($_POST['Title']);
$productionCompany = trim($_POST['ProductionCompany']);
$yearReleased = trim($_POST['YearReleased']);
$director = trim($_POST['Director']);


if (isset($_POST['submitMovie'])) {
    $newMovie = new Movie(0, $title, $productionCompany, $yearReleased, $director);
    $result = $newMovie->createRecord($dbc);  
}
	
var_dump($newMovie);
var_dump($result);
var_dump($dbc);

 
if ($result) {
 	print "The query was successfully executed!<br />";
} else {
 	print "The query could not be executed!<br />"; 
} 

?>
</body>
</html>
