<!DOCTYPE html>
<html>
<head>
<title>Insert Inventory</title>
</head>
<body style="background-color: rgb(229,243,247);">
<?php
// Set the variables for the database access:
require_once('includes/initialize.php');

/* This page receives and handles the data generated by "insertInventoryForm.html". */
// Trim the incoming data.

$Title = trim($_POST['Title']);
$ProductionCompany = trim($_POST['ProductionCompany']);
$YearReleased = trim($_POST['YearReleased']);

if (isset($_POST['submitMovie'])) {
    $Director = trim($_POST['Director']);
    $newMovie = new Movie(0, $Title, $ProductionCompany, $YearReleased, $Director);
    $result = $newMovie->createRecord($dbc);  
} else {
    $Album = trim($_POST['Album']);
    $newMusic = new Music(0, $Title, $ProductionCompany, $YearReleased, $Album);
    $result = $newMusic->createRecord($dbc);      
}
 
if ($result) {
 	print "The query was successfully executed!<br />";
} else {
 	print "The query could not be executed!<br />"; 
} 

?>
</body>
</html>
